trigger:
- add-azure-pipeline

pool:
  vmImage: 'vs2017-win2016'

variables:
  TEST: 'all'
#  LOG: 'debug'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run test-junit
  displayName: 'npm test'

  # Publish Test Results
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    testResultsFiles: 'test-results.xml'